spring.application.name=eventmanager
#=======================================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/eventfr
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#=======================================================================================
server.address=0.0.0.0
server.port=8080

jwt.secret=MarquiseSecretKeyForJWT2024VeryLongAndSecureDoNotShareInProduction
jwt.expiration=86400000
cors.allowed-origins=*