spring.application.name=eventmanager

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#=======================================================================================
server.address=0.0.0.0
server.port=8080

jwt.secret=MarquiseSecretKeyForJWT2024VeryLongAndSecureDoNotShareInProduction
jwt.expiration=86400000
cors.allowed-origins=*