spring.application.name=eventmanager
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#=======================================================================================
server.address=0.0.0.0
server.port=8080

jwt.secret=MarquiseSecretKeyForJWT2024VeryLongAndSecureDoNotShareInProduction
jwt.expiration=86400000
cors.allowed-origins=*